/**
 * Zod validation schemas for all API request bodies.
 * Used both server-side (authoritative) and optionally client-side
 * for early UI feedback.
 */

import { z } from "zod";

// ─── Auth ─────────────────────────────────────────────────────────────────────

export const registerSchema = z.object({
  email: z
    .string()
    .email("Please enter a valid email address")
    .toLowerCase()
    .trim(),
  password: z
    .string()
    .min(8, "Password must be at least 8 characters")
    .max(100, "Password is too long"),
  username: z
    .string()
    .min(3, "Username must be at least 3 characters")
    .max(30, "Username must be at most 30 characters")
    .trim()
    .regex(
      /^[a-zA-Z0-9_-]+$/,
      "Username can only contain letters, numbers, underscores, and hyphens"
    ),
  timezone: z
    .string()
    .default("UTC")
    .refine((tz) => {
      try {
        Intl.DateTimeFormat(undefined, { timeZone: tz });
        return true;
      } catch {
        return false;
      }
    }, "Invalid timezone"),
});

export type RegisterInput = z.infer<typeof registerSchema>;

// ─── Tasks ────────────────────────────────────────────────────────────────────

const TASK_CATEGORIES = [
  "Strength",
  "Intellect",
  "Discipline",
  "Creativity",
  "Social",
] as const;

const TASK_DIFFICULTIES = [
  "Trivial",
  "Easy",
  "Medium",
  "Hard",
  "Epic",
] as const;

const TASK_RECURRENCES = ["One-Off", "Daily", "Weekly"] as const;

export const createTaskSchema = z.object({
  title: z
    .string()
    .min(1, "Task title cannot be empty")
    .max(200, "Task title cannot exceed 200 characters")
    .trim()
    .refine((t) => t.trim().length > 0, "Task title cannot be whitespace only"),
  description: z
    .string()
    .max(1000, "Description cannot exceed 1000 characters")
    .trim()
    .optional()
    .default(""),
  category: z.enum(TASK_CATEGORIES, {
    error: `Category must be one of: ${TASK_CATEGORIES.join(", ")}`,
  }),
  difficulty: z.enum(TASK_DIFFICULTIES, {
    error: `Difficulty must be one of: ${TASK_DIFFICULTIES.join(", ")}`,
  }),
  recurrence: z.enum(TASK_RECURRENCES).default("One-Off"),
});

export type CreateTaskInput = z.infer<typeof createTaskSchema>;

export const updateTaskSchema = z.object({
  title: z
    .string()
    .min(1, "Task title cannot be empty")
    .max(200, "Task title cannot exceed 200 characters")
    .trim()
    .refine((t) => t.trim().length > 0, "Task title cannot be whitespace only")
    .optional(),
  description: z
    .string()
    .max(1000, "Description cannot exceed 1000 characters")
    .trim()
    .optional(),
  category: z.enum(TASK_CATEGORIES).optional(),
  difficulty: z.enum(TASK_DIFFICULTIES).optional(),
  recurrence: z.enum(TASK_RECURRENCES).optional(),
  isArchived: z.boolean().optional(),
});

export type UpdateTaskInput = z.infer<typeof updateTaskSchema>;

// ─── Task Completion ──────────────────────────────────────────────────────────

export const completeTaskSchema = z.object({
  /**
   * UUID v4 generated by the client before sending.
   * Stored with a unique index — prevents double-awards on retries.
   * The server NEVER accepts xp, gold, or any reward field from the client.
   */
  clientRequestId: z
    .string()
    .uuid("clientRequestId must be a valid UUID v4"),
});

export type CompleteTaskInput = z.infer<typeof completeTaskSchema>;

// ─── Shop ─────────────────────────────────────────────────────────────────────

export const purchaseSchema = z.object({
  clientRequestId: z
    .string()
    .uuid("clientRequestId must be a valid UUID v4"),
});

export type PurchaseInput = z.infer<typeof purchaseSchema>;
