/**
 * TaskCompletion Mongoose Model — Immutable Audit Log
 *
 * CRITICAL: Documents in this collection are NEVER updated or deleted.
 * They represent the authoritative, append-only history of all task
 * completions. XP and Gold shown here are the server-computed values
 * at the exact moment of completion.
 *
 * The `clientRequestId` field is a UUID v4 generated by the client and
 * stored with a unique index — this provides idempotency, preventing
 * double-awards if the same request is replayed (network retry, optimistic
 * UI duplicate, multi-tab simultaneous tap, etc.).
 */

import mongoose, { Schema, Document, Model } from "mongoose";

export interface ITaskCompletion extends Document {
  _id: mongoose.Types.ObjectId;
  taskId: mongoose.Types.ObjectId;
  userId: mongoose.Types.ObjectId;
  taskSnapshot: {
    title: string;
    category: string;
    difficulty: string;
  };
  xpAwarded: number;
  goldAwarded: number;
  attributeXpAwarded: number; // XP added to the specific attribute
  clientRequestId: string; // UUID v4, unique — idempotency key
  streakDayDate: string; // YYYY-MM-DD in user's timezone, for streak calc
  completedAt: Date; // Server-generated, never client-supplied
}

const TaskCompletionSchema = new Schema<ITaskCompletion>(
  {
    taskId: {
      type: Schema.Types.ObjectId,
      ref: "Task",
      required: true,
    },
    userId: {
      type: Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    taskSnapshot: {
      title: { type: String, required: true },
      category: { type: String, required: true },
      difficulty: { type: String, required: true },
    },
    xpAwarded: {
      type: Number,
      required: true,
      min: 0,
    },
    goldAwarded: {
      type: Number,
      required: true,
      min: 0,
    },
    attributeXpAwarded: {
      type: Number,
      required: true,
      min: 0,
    },
    clientRequestId: {
      type: String,
      required: true,
      unique: true, // Enforces exactly-once processing
      index: true,
    },
    streakDayDate: {
      type: String,
      required: true,
    },
    completedAt: {
      type: Date,
      default: () => new Date(), // Always server-set
    },
  },
  {
    // No `timestamps: true` — we manage `completedAt` manually and explicitly
    // to make it crystal clear this is a server-generated, non-updatable field.
    versionKey: false,
  }
);

// Indexes for history page queries
TaskCompletionSchema.index({ userId: 1, completedAt: -1 });
TaskCompletionSchema.index({ taskId: 1, completedAt: -1 });

const TaskCompletion: Model<ITaskCompletion> =
  mongoose.models.TaskCompletion ??
  mongoose.model<ITaskCompletion>("TaskCompletion", TaskCompletionSchema);

export default TaskCompletion;
